apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jxpr8ygax-go 
  janus-idp.io/tekton: jxpr8ygax-go
  backstage.io/kubernetes-id: jxpr8ygax-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jxpr8ygax-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml