apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jxpr8ygax-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:0374e6ae4bbc38d3635f4ec62e681b8e2bdc3364@sha256:39a5e8f180fd723fa86d1cb236e58fd3b640bd19d1dbb0b7df9b678de0d287f3
          name: container-image
